### ISSUE TITLE
Reference VB issues in readme

### ISSUE THREAD

**Issue by afragen** [costdev/wpclearcache#1]
We should probably reference the VirtualBox issues in the readme.

> There are some known issues where rename() in VirtualBox can fail on shared folders
> without reporting an error properly.
> 
> More details:
> https://www.virtualbox.org/ticket/8761#comment:24
> https://www.virtualbox.org/ticket/17971

**Comment by costdev** [comment]
Added in [5cd062a](https://github.com/costdev/wpclearcache/commit/5cd062a612c0c06350dbcbed68a2ca2607ed76a0).
